SiroccoDemo::Plugins::PluginBase
IOrganizationService SiroccoDemo.Plugins.PluginBase.OrganizationService
IPluginExecutionContext SiroccoDemo.Plugins.PluginBase.Context
void SiroccoDemo.Plugins.PluginBase.Execute(IServiceProvider serviceProvider)
References SiroccoDemo.Plugins.PluginBase.ExecuteWithExceptionHandling, SiroccoDemo.Plugins.PluginBase.ExtendedExecute.
void SiroccoDemo.Plugins.PluginBase.ExtendedExecute()
Referenced by SiroccoDemo.Plugins.PluginBase.Execute.
void SiroccoDemo.Plugins.PluginBase.ExecuteWithExceptionHandling(Action action)
References SiroccoDemo.Domain.Exceptions.InvalidInputException.ValidationErrors.
Referenced by SiroccoDemo.Plugins.PluginBase.Execute, SiroccoDemo.Plugins.CreateAccountWithContactsAndNotes.ExtendedExecute, SiroccoDemo.Plugins.GetAccountContactNoteSummary.ExtendedExecute.
T SiroccoDemo.Plugins.PluginBase.ExecuteWithExceptionHandling< T >(Func< T > func)
References SiroccoDemo.Domain.Exceptions.InvalidInputException.ValidationErrors.