SiroccoDemo::APIs::Areas::HelpPage::HelpPageSampleGenerator
IDictionary<HelpPageSampleKey, Type> SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.ActualHttpMessageTypes
Gets CLR types that are used as the content of HttpRequestMessage or HttpResponseMessage.
Referenced by SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.HelpPageSampleGenerator, SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.ResolveType.
IDictionary<HelpPageSampleKey, object> SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.ActionSamples
Gets the objects that are used directly as samples for certain actions.
Referenced by SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetActionSample, SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.HelpPageSampleGenerator.
IDictionary<Type, object> SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.SampleObjects
Gets the objects that are serialized as samples by the supported formatters.
Referenced by SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSampleObject, SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.HelpPageSampleGenerator.
IList<Func<HelpPageSampleGenerator, Type, object> > SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.SampleObjectFactories
Gets factories for the objects that the supported formatters will serialize as samples. Processed in order, stopping when the factory successfully returns a non- object.
Collection includes just ObjectGenerator.GenerateObject(Type) initially. Use SampleObjectFactories.Insert(0,func) to provide an override and SampleObjectFactories.Add(func) to provide a fallback.
Referenced by SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSampleObject, SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.HelpPageSampleGenerator.
SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.HelpPageSampleGenerator()
Initializes a new instance of the HelpPageSampleGenerator class.
References SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.ActionSamples, SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.ActualHttpMessageTypes, SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.SampleObjectFactories, SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.SampleObjects.
IDictionary< MediaTypeHeaderValue, object > SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSampleRequests(ApiDescription api)
Gets the request body samples for a given ApiDescription.
api The ApiDescription. The samples keyed by media type.
References SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSample.
IDictionary< MediaTypeHeaderValue, object > SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSampleResponses(ApiDescription api)
Gets the response body samples for a given ApiDescription.
api The ApiDescription. The samples keyed by media type.
References SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSample.
virtual IDictionary< MediaTypeHeaderValue, object > SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSample(ApiDescription api, SampleDirection sampleDirection)
Gets the request or response body samples.
api The ApiDescription. sampleDirection The value indicating whether the sample is for a request or for a response. The samples keyed by media type.
References SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetActionSample, SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSampleObject, SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.ResolveType, SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.WriteSampleObjectUsingFormatter.
Referenced by SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSampleRequests, SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSampleResponses.
virtual object SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetActionSample(string controllerName, string actionName, IEnumerable< string > parameterNames, Type type, MediaTypeFormatter formatter, MediaTypeHeaderValue mediaType, SampleDirection sampleDirection)
Search for samples that are provided directly through ActionSamples.
controllerName Name of the controller. actionName Name of the action. parameterNames The parameter names. type The CLR type. formatter The formatter. mediaType The media type. sampleDirection The value indicating whether the sample is for a request or for a response. The sample that matches the parameters.
References SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.ActionSamples.
Referenced by SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSample.
virtual object SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSampleObject(Type type)
Gets the sample object that will be serialized by the formatters. First, it will look at the SampleObjects. If no sample object is found, it will try to create one using DefaultSampleObjectFactory (which wraps an ObjectGenerator) and other factories in SampleObjectFactories.
type The type. The sample object.
References SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.SampleObjectFactories, SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.SampleObjects.
Referenced by SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSample.
virtual Type SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.ResolveHttpRequestMessageType(ApiDescription api)
Resolves the actual type of System.Net.Http.ObjectContent<T> passed to the System.Net.Http.HttpRequestMessage in an action.
api The ApiDescription. The type.
References SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.ResolveType.
virtual Type SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.ResolveType(ApiDescription api, string controllerName, string actionName, IEnumerable< string > parameterNames, SampleDirection sampleDirection, out Collection< MediaTypeFormatter > formatters)
Resolves the type of the action parameter or return value when HttpRequestMessage or HttpResponseMessage is used.
api The ApiDescription. controllerName Name of the controller. actionName Name of the action. parameterNames The parameter names. sampleDirection The value indicating whether the sample is for a request or a response. formatters The formatters.
References SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.ActualHttpMessageTypes.
Referenced by SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSample, SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.ResolveHttpRequestMessageType.
virtual object SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.WriteSampleObjectUsingFormatter(MediaTypeFormatter formatter, object value, Type type, MediaTypeHeaderValue mediaType)
Writes the sample object using formatter.
formatter The formatter. value The value. type The type. mediaType Type of the media.
Referenced by SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetSample.
static Exception SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.UnwrapException(Exception exception)
static object SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.DefaultSampleObjectFactory(HelpPageSampleGenerator sampleGenerator, Type type)
static string SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.TryFormatJson(string str)
static string SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.TryFormatXml(string str)
static bool SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.IsFormatSupported(SampleDirection sampleDirection, MediaTypeFormatter formatter, Type type)
static object SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.WrapSampleIfString(object sample)
IEnumerable< KeyValuePair< HelpPageSampleKey, object > > SiroccoDemo.APIs.Areas.HelpPage.HelpPageSampleGenerator.GetAllActionSamples(string controllerName, string actionName, IEnumerable< string > parameterNames, SampleDirection sampleDirection)