var _enum_value_description_8cs =
[
    [ "SiroccoDemo.APIs.Areas.HelpPage.ModelDescriptions.EnumValueDescription", "class_sirocco_demo_1_1_a_p_is_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_enum_value_description.html", "class_sirocco_demo_1_1_a_p_is_1_1_areas_1_1_help_page_1_1_model_descriptions_1_1_enum_value_description" ]
];