var _i_create_account_with_contacts_and_notes_service_8cs =
[
    [ "SiroccoDemo.Application.Services.ICreateAccountWithContactsAndNotesService", "interface_sirocco_demo_1_1_application_1_1_services_1_1_i_create_account_with_contacts_and_notes_service.html", "interface_sirocco_demo_1_1_application_1_1_services_1_1_i_create_account_with_contacts_and_notes_service" ]
];